# preprocess

```{r}
rm(list = ls())
library(tidyverse)
library(rnhanesdata)
# select 'good' data
# subsets accelerometry data by total wear/non-wear time criteria
keep_inx <- exclude_accel(act = PAXINTEN_D, flags = Flags_D)
accel_good_D <- PAXINTEN_D[keep_inx,] 
flags_good_D <- Flags_D[keep_inx,]

# participants' ID wearing monitor for 7 consecutive days
MIN_name = grep('MIN',colnames(accel_good_D),value = T)
SEQN_7days = data.frame(SEQN = accel_good_D[,'SEQN'],accel_good_D[,MIN_name] * flags_good_D[,MIN_name]) %>% 
  group_by(SEQN) %>% summarise(num = n()) %>% filter(num==7) %>% select(SEQN)

# dot multiply bwtween flag matrix and activity count matrix 
# average over days
MINdata = data.frame(SEQN = accel_good_D[,'SEQN'],accel_good_D[,MIN_name] * flags_good_D[,MIN_name]) %>%
  group_by(SEQN) %>% summarise_each(funs(mean)) %>% 
  filter(SEQN %in% SEQN_7days$SEQN) %>% na.omit()



```



# pincipal component analysis
```{r}

if(F){
  pca_model = prcomp(MINdata %>% select(-SEQN),
                     center = T,
                     scale. = T)
  save(pca_model,file= 'pca_model.rda')
}
load(file = 'pca_model.rda')

# include participants' correspondent covariates with PC loadings 
analyticData = data.frame(SEQN=MINdata$SEQN,
                          pca_model$x) %>% 
  inner_join(Covariate_D %>% select(SEQN,Race,Gender,RIDAGEYR,BMI),by = 'SEQN') %>% 
  na.omit()

# > quantile(analyticData$BMI,probs = 0.05)
#      5% 
# 16.238 
# > quantile(analyticData$BMI,probs = 0.95)
#    95% 
# 37.563
# omit outliers
analyticData = analyticData %>% filter(15 <BMI & BMI< 40)
save(analyticData, file = 'analyticData.rda')

```

# plot PC loadings and screeplot of PCA results

```{r}

rm(list = ls())
load(file = 'pca_model.rda')

library(factoextra)
fviz_eig(pca_model)

temp = pca_model$rotation %>% data.frame()

gs = lapply(1:8, function(i) {
  ggplot(temp) + 
    aes(x = 1:nrow(temp)/60,y = unlist(temp[,i])) + 
    geom_line() +
    labs(x = "Time of Day", y = paste0("Loadings on PC",i)) +
    theme(axis.title.y = element_text(size = rel(0.9)))
})
library(gridExtra)
do.call(grid.arrange,c(gs,nrow = 3))
```



# correlation analysis and RF
```{r}

rm(list = ls())
load(file = 'analyticData.rda')

# correlation anaysis
PCnames = paste('PC',1:5,sep = '')
y = analyticData[,c('RIDAGEYR','Race','Gender','BMI',PCnames)] %>% na.omit()

# change factor (Race/Gender) to numeric
y_cor <- as.data.frame(
  lapply(y, function (x) if (is.factor(x)) unclass(x) %>% as.numeric  else x))
res_cor = cor(y_cor)
library(corrplot)
corrplot(res_cor,
         metho = 'color',
         type = 'upper',
         order = 'hclust',
         addCoef.col = "black",
         diag = F)

# rank variable importance using randomforest
library(randomForest)
if(F){
  fit = randomForest(BMI ~ ., data = y,ntree = 501,
                     importance = T)
  save(fit,file = 'rffit.rda')
}
load(file = 'rffit.rda')
importance(fit)
varImpPlot(fit)


```


# cross validation
```{r}
rm(list = ls())
library(caret)
load(file = 'analyticData.rda')
res_RMSE = c()
res_Rsquared = c()
if(F){
  for(i in 1:50){
    PCnames = paste('PC',1:i,sep = '')
    train.control <- trainControl(method = "cv", number = 10)
    dat = analyticData[,c('RIDAGEYR','Race','Gender','BMI',PCnames)]
    model <- caret::train(BMI ~., data = dat, method = "lm",
                          trControl = train.control)
    res_RMSE = c(res_RMSE, model$results$RMSE)
    res_Rsquared = c(res_Rsquared, model$results$Rsquared)
    
  }
  save(res_RMSE,res_Rsquared, file = 'CV_50PCs.rda')
}

load(file = 'CV_50PCs.rda')
g1 = ggplot(data.frame(res_RMSE)) + 
  aes(x = 1:length(res_RMSE), y = res_RMSE) +
  geom_line()+
  # geom_smooth(se = TRUE, method = 'lm')+
  geom_smooth(se = TRUE, method =  'auto',color = 'blue') +
  labs(x = 'Number of Principal Components Used in Cross-Validation',y = 'Root Mean Square Error ')

g2 = ggplot(data.frame(res_Rsquared)) + 
  aes(x = 1:length(res_Rsquared), y = res_Rsquared) +
  geom_line()+
  # geom_smooth(se = TRUE, method = 'lm')+
  geom_smooth(se = TRUE, method =  'auto',color = 'blue') + 
  labs(x = 'Number of Principal Components Used in Cross-Validation',y = 'R-squared')

which(res_RMSE==min(res_RMSE))
which(res_Rsquared==max(res_Rsquared))
grid.arrange(g1,g2)

```


# ANOVA
```{r}
rm(list = ls())
load(file = 'analyticData.rda')
models = list()
for (i in 1:14){
  PCnames = paste('PC',1:i,sep = '')
  y = analyticData[,c('RIDAGEYR','Race','Gender','BMI',PCnames)] %>% na.omit()
  set.seed(111)
  trainidx = sample(nrow(y),0.7*nrow(y))
  model = lm(BMI ~., data = y, subset = trainidx)
  models = c(models,list(model))
}


do.call(anova,models)

```

# results
```{r}
rm(list =ls())
load(file = 'analyticData.rda')
PCnames = paste('PC',1:8,sep = '')
y = analyticData[,c('RIDAGEYR','Race','Gender','BMI',PCnames)] %>% na.omit()
yTrue = y$BMI

set.seed(111)
trainidx = sample(nrow(y),0.7*nrow(y))

fit = lm(BMI ~ .,data = y, subset = trainidx)
summary(fit)

yPred = predict(fit,y[-trainidx,])
yTrue = yTrue[-trainidx]
result = cbind(yPred,
               yTrue) %>% as.data.frame() %>% na.omit()

ggplot(data=result , aes(x = 1:dim(result)[1])) + 
  geom_line(aes(y = yPred),color = 'red') + 
  geom_line(aes(y = yTrue),color = 'blue') +
  labs(x = 'Patients', y = 'BMI',
       title  = "PCs + Age + Race + Gender")

ggplot(data = result) + 
  aes(x = yTrue, y = yPred) +
  geom_point()+
  # geom_smooth(se = TRUE, method = 'lm')+
  geom_smooth(se = TRUE, method =  'auto',color = 'red') +
  labs(y = 'Predicted BMI', x = 'Actual BMI') +
  theme(axis.text=element_text(size=20),
        axis.title=element_text(size=20))

plot(fit,which = 1)


# choose the first 14 PCs
PCnames = paste('PC',1:14,sep = '')
y = analyticData[,c('RIDAGEYR','Race','Gender','BMI',PCnames)] %>% na.omit()
yTrue = y$BMI
set.seed(111)
trainidx = sample(nrow(y),0.7*nrow(y))
fit2 = lm(BMI ~ .,data = y, subset = trainidx)




# plot table
library(sjPlot)
tab_model(fit,
          ci.hyphen = ", ",
          string.ci = "CI (95%)",
          string.p = "P-Value",
          dv.labels = "Regression Model using the first 14 PCs")
tab_model(fit2,
          ci.hyphen = ", ",
          string.ci = "CI (95%)",
          string.p = "P-Value",
          dv.labels = "Regression Model using the first 8 PCs")

tab_model(fit,fit2,
          ci.hyphen = ", ",
          show.ci = FALSE,
          dv.labels = c("Regression Model using the first 14 PCs",
                        "Regression Model using the first 8 PCs"))

```

